## ENV

In [21]:
import requests
import pandas as pd
import json

## Data

* data : https://finance.naver.com/marketindex/worldDailyQuote.nhn?marketindexCd=OIL_CL&fdtc=2&page=2

In [3]:
wti_url = "https://finance.naver.com/marketindex/worldDailyQuote.nhn?marketindexCd=OIL_CL&fdtc=2&page=1"

In [8]:
original_wti = pd.read_html(wti_url)[0]

In [9]:
wti_url = "https://finance.naver.com/marketindex/worldDailyQuote.nhn?marketindexCd=OIL_CL&fdtc=2&page={}"
for x in range(2,6):
    original_wti = original_wti.append(pd.read_html(wti_url.format(x))[0])

* 아래 결과에서 index가 중복되어 있다는 것을 주목할 것

In [10]:
original_wti

           날짜   파실 때  보내실 때     받으실 때
0  2020.05.26  34.35   1.10    +3.30%
1  2020.05.22  33.25   0.67    -1.97%
2  2020.05.21  33.92   0.43    +1.28%
3  2020.05.20  33.49   1.53    +4.78%
4  2020.05.19  31.96   0.31    +0.97%
5  2020.05.18  31.82   2.39    +8.12%
6  2020.05.15  29.43   1.87    +6.78%
0  2020.05.14  27.56   2.27    +8.97%
1  2020.05.13  25.29   0.49    -1.90%
2  2020.05.12  25.78   1.64    +6.79%
3  2020.05.11  24.14   0.60    -2.42%
4  2020.05.08  24.74   1.19    +5.05%
5  2020.05.07  23.55   0.44    -1.83%
6  2020.05.06  23.99   0.57    -2.32%
0  2020.05.05  24.56   4.17   +20.45%
1  2020.05.04  20.39   0.61    +3.08%
2  2020.05.01  19.78   0.94    +4.98%
3  2020.04.30  18.84   3.78   +25.09%
4  2020.04.29  15.06   2.72   +22.04%
5  2020.04.28  12.34   0.44    -3.44%
6  2020.04.27  12.78   4.16   -24.55%
0  2020.04.24  16.94   0.44    +2.66%
1  2020.04.23  16.50   2.72   +19.73%
2  2020.04.22  13.78   2.21   +19.10%
3  2020.04.21  10.01  47.64  +126.60%
4  2020.04.20 -37.63  55.90  -305.96%
5  2020.04.17  18.27   1.60    -8.05%
6  2020.04.16  19.87   0.00     0.00%
0  2020.04.15  19.87   0.24    -1.19%
1  2020.04.14  20.11   2.30   -10.26%
2  2020.04.13  22.41   0.35    -1.53%
3  2020.04.09  22.76   2.33    -9.28%
4  2020.04.08  25.09   1.46    +6.17%
5  2020.04.07  23.63   2.45    -9.39%
6  2020.04.06  26.08   2.26    -7.97%

* sk이노 데이터: "https://finance.naver.com/item/sise_day.nhn?code=096770&page={}"

In [15]:
sk = "https://finance.naver.com/item/sise_day.nhn?code=096770&page={}"
original_sk_df = pd.DataFrame()
for x in range(1, 6):
    original_sk_df = original_sk_df.append( pd.read_html(sk.format(x) )[0], ignore_index = True)

* ignore_index는 append 대상이 되는 개별 df의 index를 ignore 하는 것

In [16]:
original_sk_df

            날짜        종가      전일비        시가        고가        저가        거래량
0          NaN       NaN      NaN       NaN       NaN       NaN        NaN
1   2020.05.27  122500.0   1500.0  122500.0  129000.0  118000.0  1834553.0
2   2020.05.26  121000.0  15000.0  106000.0  122500.0  105500.0  2739083.0
3   2020.05.25  106000.0   2500.0  104000.0  106500.0  102000.0   564404.0
4   2020.05.22  103500.0   3000.0  106500.0  107000.0  102000.0   686662.0
..         ...       ...      ...       ...       ...       ...        ...
70  2020.03.18   70900.0   7000.0   77300.0   77800.0   70900.0   919817.0
71  2020.03.17   77900.0   2300.0   75100.0   79400.0   75100.0  1006085.0
72  2020.03.16   80200.0   6300.0   86000.0   86900.0   80200.0  1113686.0
73  2020.03.13   86500.0   5900.0   83300.0   87200.0   82500.0  1232107.0
74         NaN       NaN      NaN       NaN       NaN       NaN        NaN

[75 rows x 7 columns]

* NaN을 drop

In [18]:
original_sk_df.dropna(inplace=True)

In [19]:
original_sk_df

            날짜        종가      전일비        시가        고가        저가        거래량
1   2020.05.27  122500.0   1500.0  122500.0  129000.0  118000.0  1834553.0
2   2020.05.26  121000.0  15000.0  106000.0  122500.0  105500.0  2739083.0
3   2020.05.25  106000.0   2500.0  104000.0  106500.0  102000.0   564404.0
4   2020.05.22  103500.0   3000.0  106500.0  107000.0  102000.0   686662.0
5   2020.05.21  106500.0   3000.0  106000.0  110000.0  105500.0  1120684.0
9   2020.05.20  103500.0      0.0  101500.0  104500.0  101000.0   614306.0
10  2020.05.19  103500.0   6700.0  101500.0  104000.0  100000.0  1724747.0
11  2020.05.18   96800.0   2400.0   96000.0   96900.0   94400.0   567019.0
12  2020.05.15   94400.0    800.0   94900.0   96000.0   94200.0   480497.0
13  2020.05.14   93600.0   1900.0   94500.0   94800.0   93000.0   490652.0
16  2020.05.13   95500.0    100.0   95000.0   95500.0   93000.0   608052.0
17  2020.05.12   95400.0   2100.0   97000.0   97400.0   95000.0   642196.0
18  2020.05.11   97500.0   1100.0   99200.0   99600.0   97500.0   466477.0
19  2020.05.08   98600.0    100.0   99000.0   99500.0   98600.0   448962.0
20  2020.05.07   98700.0   1300.0   99200.0   99500.0   97800.0   670766.0
24  2020.05.06  100000.0   3300.0   99200.0  103000.0   99200.0  1419621.0
25  2020.05.04   96700.0   1600.0   99900.0   99900.0   96500.0   831689.0
26  2020.04.29   98300.0   1800.0   97000.0  100500.0   97000.0   889335.0
27  2020.04.28   96500.0   1100.0   96200.0   97700.0   95700.0   655250.0
28  2020.04.27   97600.0      0.0   97600.0   98900.0   97600.0   454652.0
31  2020.04.24   97600.0   1800.0  100500.0  101000.0   97500.0   619467.0
32  2020.04.23   99400.0   3100.0   98700.0  100000.0   97300.0   914524.0
33  2020.04.22   96300.0   2200.0   96500.0   97300.0   95100.0   751758.0
34  2020.04.21   98500.0    500.0   97500.0  101000.0   95300.0   975923.0
35  2020.04.20   99000.0   1300.0   99200.0  102500.0   98300.0   898140.0
39  2020.04.17   97700.0   1000.0   97300.0   98500.0   97100.0   878699.0
40  2020.04.16   96700.0    500.0   95300.0   98000.0   94300.0   733830.0
41  2020.04.14   97200.0    900.0   97100.0   99300.0   96500.0   682589.0
42  2020.04.13   96300.0   4200.0   99800.0  100500.0   95800.0   778610.0
43  2020.04.10  100500.0   2500.0   95300.0  101500.0   95300.0  1300475.0
46  2020.04.09   98000.0   4400.0   96800.0   98000.0   95000.0  1180802.0
47  2020.04.08   93600.0    700.0   92600.0   95900.0   92200.0   828451.0
48  2020.04.07   94300.0    100.0   96500.0   96900.0   91900.0  1161168.0
49  2020.04.06   94400.0   4700.0   91100.0   95500.0   90000.0  1393130.0
50  2020.04.03   89700.0    700.0   95800.0   98500.0   87800.0  1788505.0
54  2020.04.02   90400.0   7900.0   83100.0   93500.0   81400.0  2074973.0
55  2020.04.01   82500.0   4500.0   85100.0   87000.0   82500.0   835614.0
56  2020.03.31   87000.0    900.0   88000.0   88200.0   84500.0  1027447.0
57  2020.03.30   86100.0   1600.0   83400.0   87700.0   81700.0  1151182.0
58  2020.03.27   87700.0   2700.0   89600.0   90500.0   85200.0  1746990.0
61  2020.03.26   85000.0   5000.0   91000.0  100500.0   84900.0  3277516.0
62  2020.03.25   90000.0  18000.0   79000.0   91300.0   75700.0  2877009.0
63  2020.03.24   72000.0  11700.0   63100.0   73200.0   61500.0  1571585.0
64  2020.03.23   60300.0   4500.0   58500.0   62900.0   57800.0  1162459.0
65  2020.03.20   64800.0   7500.0   61000.0   65100.0   59100.0  1719407.0
69  2020.03.19   57300.0  13600.0   70900.0   72300.0   55100.0  2188651.0
70  2020.03.18   70900.0   7000.0   77300.0   77800.0   70900.0   919817.0
71  2020.03.17   77900.0   2300.0   75100.0   79400.0   75100.0  1006085.0
72  2020.03.16   80200.0   6300.0   86000.0   86900.0   80200.0  1113686.0
73  2020.03.13   86500.0   5900.0   83300.0   87200.0   82500.0  1232107.0

## concat

* 가로 혹은 세로로 붙일 수 있음
* pandas.concat(objs, axis=0, join='outer', join_axes=None, ignore_index=False, keys=None, levels=None, names=None, verify_integrity=False, sort=None, copy=True)
* DataFrame에 컬럼 및 행을 추가할 때 사용함
* pd.concat()의 매개변수로 axis 값을 1로 지정하면 열, 0으로 지정하면 행으로 처리
* concat는 concatenation의 단어에서 따옴

In [22]:
sk = "https://finance.naver.com/item/sise_day.nhn?code=096770&page={}"
original_sk_df = pd.DataFrame()
for x in range(1, 6):
    original_sk_df = pd.concat([original_sk_df, pd.read_html(sk.format(x) )[0]])

In [23]:
original_sk_df

            날짜        종가      전일비        시가        고가        저가        거래량
0          NaN       NaN      NaN       NaN       NaN       NaN        NaN
1   2020.05.27  122000.0   1000.0  122500.0  129000.0  118000.0  1853126.0
2   2020.05.26  121000.0  15000.0  106000.0  122500.0  105500.0  2739083.0
3   2020.05.25  106000.0   2500.0  104000.0  106500.0  102000.0   564404.0
4   2020.05.22  103500.0   3000.0  106500.0  107000.0  102000.0   686662.0
..         ...       ...      ...       ...       ...       ...        ...
10  2020.03.18   70900.0   7000.0   77300.0   77800.0   70900.0   919817.0
11  2020.03.17   77900.0   2300.0   75100.0   79400.0   75100.0  1006085.0
12  2020.03.16   80200.0   6300.0   86000.0   86900.0   80200.0  1113686.0
13  2020.03.13   86500.0   5900.0   83300.0   87200.0   82500.0  1232107.0
14         NaN       NaN      NaN       NaN       NaN       NaN        NaN

[75 rows x 7 columns]

In [24]:
original_sk_df.dropna(inplace=True)

In [25]:
original_sk_df

            날짜        종가      전일비        시가        고가        저가        거래량
1   2020.05.27  122000.0   1000.0  122500.0  129000.0  118000.0  1853126.0
2   2020.05.26  121000.0  15000.0  106000.0  122500.0  105500.0  2739083.0
3   2020.05.25  106000.0   2500.0  104000.0  106500.0  102000.0   564404.0
4   2020.05.22  103500.0   3000.0  106500.0  107000.0  102000.0   686662.0
5   2020.05.21  106500.0   3000.0  106000.0  110000.0  105500.0  1120684.0
9   2020.05.20  103500.0      0.0  101500.0  104500.0  101000.0   614306.0
10  2020.05.19  103500.0   6700.0  101500.0  104000.0  100000.0  1724747.0
11  2020.05.18   96800.0   2400.0   96000.0   96900.0   94400.0   567019.0
12  2020.05.15   94400.0    800.0   94900.0   96000.0   94200.0   480497.0
13  2020.05.14   93600.0   1900.0   94500.0   94800.0   93000.0   490652.0
1   2020.05.13   95500.0    100.0   95000.0   95500.0   93000.0   608052.0
2   2020.05.12   95400.0   2100.0   97000.0   97400.0   95000.0   642196.0
3   2020.05.11   97500.0   1100.0   99200.0   99600.0   97500.0   466477.0
4   2020.05.08   98600.0    100.0   99000.0   99500.0   98600.0   448962.0
5   2020.05.07   98700.0   1300.0   99200.0   99500.0   97800.0   670766.0
9   2020.05.06  100000.0   3300.0   99200.0  103000.0   99200.0  1419621.0
10  2020.05.04   96700.0   1600.0   99900.0   99900.0   96500.0   831689.0
11  2020.04.29   98300.0   1800.0   97000.0  100500.0   97000.0   889335.0
12  2020.04.28   96500.0   1100.0   96200.0   97700.0   95700.0   655250.0
13  2020.04.27   97600.0      0.0   97600.0   98900.0   97600.0   454652.0
1   2020.04.24   97600.0   1800.0  100500.0  101000.0   97500.0   619467.0
2   2020.04.23   99400.0   3100.0   98700.0  100000.0   97300.0   914524.0
3   2020.04.22   96300.0   2200.0   96500.0   97300.0   95100.0   751758.0
4   2020.04.21   98500.0    500.0   97500.0  101000.0   95300.0   975923.0
5   2020.04.20   99000.0   1300.0   99200.0  102500.0   98300.0   898140.0
9   2020.04.17   97700.0   1000.0   97300.0   98500.0   97100.0   878699.0
10  2020.04.16   96700.0    500.0   95300.0   98000.0   94300.0   733830.0
11  2020.04.14   97200.0    900.0   97100.0   99300.0   96500.0   682589.0
12  2020.04.13   96300.0   4200.0   99800.0  100500.0   95800.0   778610.0
13  2020.04.10  100500.0   2500.0   95300.0  101500.0   95300.0  1300475.0
1   2020.04.09   98000.0   4400.0   96800.0   98000.0   95000.0  1180802.0
2   2020.04.08   93600.0    700.0   92600.0   95900.0   92200.0   828451.0
3   2020.04.07   94300.0    100.0   96500.0   96900.0   91900.0  1161168.0
4   2020.04.06   94400.0   4700.0   91100.0   95500.0   90000.0  1393130.0
5   2020.04.03   89700.0    700.0   95800.0   98500.0   87800.0  1788505.0
9   2020.04.02   90400.0   7900.0   83100.0   93500.0   81400.0  2074973.0
10  2020.04.01   82500.0   4500.0   85100.0   87000.0   82500.0   835614.0
11  2020.03.31   87000.0    900.0   88000.0   88200.0   84500.0  1027447.0
12  2020.03.30   86100.0   1600.0   83400.0   87700.0   81700.0  1151182.0
13  2020.03.27   87700.0   2700.0   89600.0   90500.0   85200.0  1746990.0
1   2020.03.26   85000.0   5000.0   91000.0  100500.0   84900.0  3277516.0
2   2020.03.25   90000.0  18000.0   79000.0   91300.0   75700.0  2877009.0
3   2020.03.24   72000.0  11700.0   63100.0   73200.0   61500.0  1571585.0
4   2020.03.23   60300.0   4500.0   58500.0   62900.0   57800.0  1162459.0
5   2020.03.20   64800.0   7500.0   61000.0   65100.0   59100.0  1719407.0
9   2020.03.19   57300.0  13600.0   70900.0   72300.0   55100.0  2188651.0
10  2020.03.18   70900.0   7000.0   77300.0   77800.0   70900.0   919817.0
11  2020.03.17   77900.0   2300.0   75100.0   79400.0   75100.0  1006085.0
12  2020.03.16   80200.0   6300.0   86000.0   86900.0   80200.0  1113686.0
13  2020.03.13   86500.0   5900.0   83300.0   87200.0   82500.0  1232107.0

In [27]:
original = original_wti.copy()

In [28]:
sk_df = original_sk_df.copy()

* 컬럼 기준 merge

In [33]:
cut_wti = original.iloc[:5]

In [37]:
cut_wti

           날짜   파실 때  보내실 때   받으실 때
0  2020.05.26  34.35   1.10  +3.30%
1  2020.05.22  33.25   0.67  -1.97%
2  2020.05.21  33.92   0.43  +1.28%
3  2020.05.20  33.49   1.53  +4.78%
4  2020.05.19  31.96   0.31  +0.97%

In [34]:
cut_sk_df = sk_df.iloc[1:6]

In [38]:
cut_sk_df

           날짜        종가      전일비        시가        고가        저가        거래량
2  2020.05.26  121000.0  15000.0  106000.0  122500.0  105500.0  2739083.0
3  2020.05.25  106000.0   2500.0  104000.0  106500.0  102000.0   564404.0
4  2020.05.22  103500.0   3000.0  106500.0  107000.0  102000.0   686662.0
5  2020.05.21  106500.0   3000.0  106000.0  110000.0  105500.0  1120684.0
9  2020.05.20  103500.0      0.0  101500.0  104500.0  101000.0   614306.0

* concat이 merge 할 때, 동일한 행의 판단은 index 기준

In [36]:
pd.concat([cut_wti, cut_sk_df], axis = 1)

,날짜,파실 때,보내실 때,받으실 때,날짜,종가,전일비,시가,고가,저가,거래량
0,2020.05.26,34.35,1.10,+3.30%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020.05.22,33.25,0.67,-1.97%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020.05.21,33.92,0.43,+1.28%,2020.05.26,121000.0,15000.0,106000.0,122500.0,105500.0,2739083.0
3,2020.05.20,33.49,1.53,+4.78%,2020.05.25,106000.0,2500.0,104000.0,106500.0,102000.0,564404.0
4,2020.05.19,31.96,0.31,+0.97%,2020.05.22,103500.0,3000.0,106500.0,107000.0,102000.0,686662.0
5,NaN,NaN,NaN,NaN,2020.05.21,106500.0,3000.0,106000.0,110000.0,105500.0,1120684.0
9,NaN,NaN,NaN,NaN,2020.05.20,103500.0,0.0,101500.0,104500.0,101000.0,614306.0

* 컬럼을 삭제하고 날짜 index로 통일

In [41]:
original.index = original.날짜

In [43]:
del original['날짜']

In [44]:
original

             파실 때  보내실 때     받으실 때
날짜
2020.05.26  34.35   1.10    +3.30%
2020.05.22  33.25   0.67    -1.97%
2020.05.21  33.92   0.43    +1.28%
2020.05.20  33.49   1.53    +4.78%
2020.05.19  31.96   0.31    +0.97%
2020.05.18  31.82   2.39    +8.12%
2020.05.15  29.43   1.87    +6.78%
2020.05.14  27.56   2.27    +8.97%
2020.05.13  25.29   0.49    -1.90%
2020.05.12  25.78   1.64    +6.79%
2020.05.11  24.14   0.60    -2.42%
2020.05.08  24.74   1.19    +5.05%
2020.05.07  23.55   0.44    -1.83%
2020.05.06  23.99   0.57    -2.32%
2020.05.05  24.56   4.17   +20.45%
2020.05.04  20.39   0.61    +3.08%
2020.05.01  19.78   0.94    +4.98%
2020.04.30  18.84   3.78   +25.09%
2020.04.29  15.06   2.72   +22.04%
2020.04.28  12.34   0.44    -3.44%
2020.04.27  12.78   4.16   -24.55%
2020.04.24  16.94   0.44    +2.66%
2020.04.23  16.50   2.72   +19.73%
2020.04.22  13.78   2.21   +19.10%
2020.04.21  10.01  47.64  +126.60%
2020.04.20 -37.63  55.90  -305.96%
2020.04.17  18.27   1.60    -8.05%
2020.04.16  19.87   0.00     0.00%
2020.04.15  19.87   0.24    -1.19%
2020.04.14  20.11   2.30   -10.26%
2020.04.13  22.41   0.35    -1.53%
2020.04.09  22.76   2.33    -9.28%
2020.04.08  25.09   1.46    +6.17%
2020.04.07  23.63   2.45    -9.39%
2020.04.06  26.08   2.26    -7.97%

In [46]:
sk_df.index = sk_df.날짜

In [48]:
del sk_df['날짜']

In [49]:
sk_df

                  종가      전일비        시가        고가        저가        거래량
날짜
2020.05.27  122000.0   1000.0  122500.0  129000.0  118000.0  1853126.0
2020.05.26  121000.0  15000.0  106000.0  122500.0  105500.0  2739083.0
2020.05.25  106000.0   2500.0  104000.0  106500.0  102000.0   564404.0
2020.05.22  103500.0   3000.0  106500.0  107000.0  102000.0   686662.0
2020.05.21  106500.0   3000.0  106000.0  110000.0  105500.0  1120684.0
2020.05.20  103500.0      0.0  101500.0  104500.0  101000.0   614306.0
2020.05.19  103500.0   6700.0  101500.0  104000.0  100000.0  1724747.0
2020.05.18   96800.0   2400.0   96000.0   96900.0   94400.0   567019.0
2020.05.15   94400.0    800.0   94900.0   96000.0   94200.0   480497.0
2020.05.14   93600.0   1900.0   94500.0   94800.0   93000.0   490652.0
2020.05.13   95500.0    100.0   95000.0   95500.0   93000.0   608052.0
2020.05.12   95400.0   2100.0   97000.0   97400.0   95000.0   642196.0
2020.05.11   97500.0   1100.0   99200.0   99600.0   97500.0   466477.0
2020.05.08   98600.0    100.0   99000.0   99500.0   98600.0   448962.0
2020.05.07   98700.0   1300.0   99200.0   99500.0   97800.0   670766.0
2020.05.06  100000.0   3300.0   99200.0  103000.0   99200.0  1419621.0
2020.05.04   96700.0   1600.0   99900.0   99900.0   96500.0   831689.0
2020.04.29   98300.0   1800.0   97000.0  100500.0   97000.0   889335.0
2020.04.28   96500.0   1100.0   96200.0   97700.0   95700.0   655250.0
2020.04.27   97600.0      0.0   97600.0   98900.0   97600.0   454652.0
2020.04.24   97600.0   1800.0  100500.0  101000.0   97500.0   619467.0
2020.04.23   99400.0   3100.0   98700.0  100000.0   97300.0   914524.0
2020.04.22   96300.0   2200.0   96500.0   97300.0   95100.0   751758.0
2020.04.21   98500.0    500.0   97500.0  101000.0   95300.0   975923.0
2020.04.20   99000.0   1300.0   99200.0  102500.0   98300.0   898140.0
2020.04.17   97700.0   1000.0   97300.0   98500.0   97100.0   878699.0
2020.04.16   96700.0    500.0   95300.0   98000.0   94300.0   733830.0
2020.04.14   97200.0    900.0   97100.0   99300.0   96500.0   682589.0
2020.04.13   96300.0   4200.0   99800.0  100500.0   95800.0   778610.0
2020.04.10  100500.0   2500.0   95300.0  101500.0   95300.0  1300475.0
2020.04.09   98000.0   4400.0   96800.0   98000.0   95000.0  1180802.0
2020.04.08   93600.0    700.0   92600.0   95900.0   92200.0   828451.0
2020.04.07   94300.0    100.0   96500.0   96900.0   91900.0  1161168.0
2020.04.06   94400.0   4700.0   91100.0   95500.0   90000.0  1393130.0
2020.04.03   89700.0    700.0   95800.0   98500.0   87800.0  1788505.0
2020.04.02   90400.0   7900.0   83100.0   93500.0   81400.0  2074973.0
2020.04.01   82500.0   4500.0   85100.0   87000.0   82500.0   835614.0
2020.03.31   87000.0    900.0   88000.0   88200.0   84500.0  1027447.0
2020.03.30   86100.0   1600.0   83400.0   87700.0   81700.0  1151182.0
2020.03.27   87700.0   2700.0   89600.0   90500.0   85200.0  1746990.0
2020.03.26   85000.0   5000.0   91000.0  100500.0   84900.0  3277516.0
2020.03.25   90000.0  18000.0   79000.0   91300.0   75700.0  2877009.0
2020.03.24   72000.0  11700.0   63100.0   73200.0   61500.0  1571585.0
2020.03.23   60300.0   4500.0   58500.0   62900.0   57800.0  1162459.0
2020.03.20   64800.0   7500.0   61000.0   65100.0   59100.0  1719407.0
2020.03.19   57300.0  13600.0   70900.0   72300.0   55100.0  2188651.0
2020.03.18   70900.0   7000.0   77300.0   77800.0   70900.0   919817.0
2020.03.17   77900.0   2300.0   75100.0   79400.0   75100.0  1006085.0
2020.03.16   80200.0   6300.0   86000.0   86900.0   80200.0  1113686.0
2020.03.13   86500.0   5900.0   83300.0   87200.0   82500.0  1232107.0

* 이렇게 날짜 기준으로 index를 통일한 후에 이것을 기준으로 concat

In [58]:
pd.concat([original, sk_df], axis =1,sort = False)

,파실 때,보내실 때,받으실 때,종가,전일비,시가,고가,저가,거래량
2020.05.26,34.35,1.10,+3.30%,121000.0,15000.0,106000.0,122500.0,105500.0,2739083.0
2020.05.22,33.25,0.67,-1.97%,103500.0,3000.0,106500.0,107000.0,102000.0,686662.0
2020.05.21,33.92,0.43,+1.28%,106500.0,3000.0,106000.0,110000.0,105500.0,1120684.0
2020.05.20,33.49,1.53,+4.78%,103500.0,0.0,101500.0,104500.0,101000.0,614306.0
2020.05.19,31.96,0.31,+0.97%,103500.0,6700.0,101500.0,104000.0,100000.0,1724747.0
2020.05.18,31.82,2.39,+8.12%,96800.0,2400.0,96000.0,96900.0,94400.0,567019.0
2020.05.15,29.43,1.87,+6.78%,94400.0,800.0,94900.0,96000.0,94200.0,480497.0
2020.05.14,27.56,2.27,+8.97%,93600.0,1900.0,94500.0,94800.0,93000.0,490652.0
2020.05.13,25.29,0.49,-1.90%,95500.0,100.0,95000.0,95500.0,93000.0,608052.0
2020.05.12,25.78,1.64,+6.79%,95400.0,2100.0,97000.0,97400.0,95000.0,642196.0
2020.05.11,24.14,0.60,-2.42%,97500.0,1100.0,99200.0,99600.0,97500.0,466477.0
2020.05.08,24.74,1.19,+5.05%,98600.0,100.0,99000.0,99500.0,98600.0,448962.0
2020.05.07,23.55,0.44,-1.83%,98700.0,1300.0,99200.0,99500.0,97800.0,670766.0
2020.05.06,23.99,0.57,-2.32%,100000.0,3300.0,99200.0,103000.0,99200.0,1419621.0
2020.05.05,24.56,4.17,+20.45%,NaN,NaN,NaN,NaN,NaN,NaN
2020.05.04,20.39,0.61,+3.08%,96700.0,1600.0,99900.0,99900.0,96500.0,831689.0
2020.05.01,19.78,0.94,+4.98%,NaN,NaN,NaN,NaN,NaN,NaN
2020.04.30,18.84,3.78,+25.09%,NaN,NaN,NaN,NaN,NaN,NaN
2020.04.29,15.06,2.72,+22.04%,98300.0,1800.0,97000.0,100500.0,97000.0,889335.0
2020.04.28,12.34,0.44,-3.44%,96500.0,1100.0,96200.0,97700.0,95700.0,655250.0
2020.04.27,12.78,4.16,-24.55%,97600.0,0.0,97600.0,98900.0,97600.0,454652.0
2020.04.24,16.94,0.44,+2.66%,97600.0,1800.0,100500.0,101000.0,97500.0,619467.0
2020.04.23,16.50,2.72,+19.73%,99400.0,3100.0,98700.0,100000.0,97300.0,914524.0
2020.04.22,13.78,2.21,+19.10%,96300.0,2200.0,96500.0,97300.0,95100.0,751758.0
2020.04.21,10.01,47.64,+126.60%,98500.0,500.0,97500.0,101000.0,95300.0,975923.0
2020.04.20,-37.63,55.90,-305.96%,99000.0,1300.0,99200.0,102500.0,98300.0,898140.0
2020.04.17,18.27,1.60,-8.05%,97700.0,1000.0,97300.0,98500.0,97100.0,878699.0
2020.04.16,19.87,0.00,0.00%,96700.0,500.0,95300.0,98000.0,94300.0,733830.0
2020.04.15,19.87,0.24,-1.19%,NaN,NaN,NaN,NaN,NaN,NaN
2020.04.14,20.11,2.30,-10.26%,97200.0,900.0,97100.0,99300.0,96500.0,682589.0
2020.04.13,22.41,0.35,-1.53%,96300.0,4200.0,99800.0,100500.0,95800.0,778610.0
2020.04.09,22.76,2.33,-9.28%,98000.0,4400.0,96800.0,98000.0,95000.0,1180802.0
2020.04.08,25.09,1.46,+6.17%,93600.0,700.0,92600.0,95900.0,92200.0,828451.0
2020.04.07,23.63,2.45,-9.39%,94300.0,100.0,96500.0,96900.0,91900.0,1161168.0
2020.04.06,26.08,2.26,-7.97%,94400.0,4700.0,91100.0,95500.0,90000.0,1393130.0
2020.05.27,NaN,NaN,NaN,122000.0,1000.0,122500.0,129000.0,118000.0,1853126.0
2020.05.25,NaN,NaN,NaN,106000.0,2500.0,104000.0,106500.0,102000.0,564404.0
2020.04.10,NaN,NaN,NaN,100500.0,2500.0,95300.0,101500.0,95300.0,1300475.0
2020.04.03,NaN,NaN,NaN,89700.0,700.0,95800.0,98500.0,87800.0,1788505.0
2020.04.02,NaN,NaN,NaN,90400.0,7900.0,83100.0,93500.0,81400.0,2074973.0
2020.04.01,NaN,NaN,NaN,82500.0,4500.0,85100.0,87000.0,82500.0,835614.0
2020.03.31,NaN,NaN,NaN,87000.0,900.0,88000.0,88200.0,84500.0,1027447.0
2020.03.30,NaN,NaN,NaN,86100.0,1600.0,83400.0,87700.0,81700.0,1151182.0
2020.03.27,NaN,NaN,NaN,87700.0,2700.0,89600.0,90500.0,85200.0,1746990.0
2020.03.26,NaN,NaN,NaN,85000.0,5000.0,91000.0,100500.0,84900.0,3277516.0
2020.03.25,NaN,NaN,NaN,90000.0,18000.0,79000.0,91300.0,75700.0,2877009.0
2020.03.24,NaN,NaN,NaN,72000.0,11700.0,63100.0,73200.0,61500.0,1571585.0
2020.03.23,NaN,NaN,NaN,60300.0,4500.0,58500.0,62900.0,57800.0,1162459.0
2020.03.20,NaN,NaN,NaN,64800.0,7500.0,61000.0,65100.0,59100.0,1719407.0
2020.03.19,NaN,NaN,NaN,57300.0,13600.0,70900.0,72300.0,55100.0,2188651.0
2020.03.18,NaN,NaN,NaN,70900.0,7000.0,77300.0,77800.0,70900.0,919817.0
2020.03.17,NaN,NaN,NaN,77900.0,2300.0,75100.0,79400.0,75100.0,1006085.0
2020.03.16,NaN,NaN,NaN,80200.0,6300.0,86000.0,86900.0,80200.0,1113686.0
2020.03.13,NaN,NaN,NaN,86500.0,5900.0,83300.0,87200.0,82500.0,1232107.0

* 함수를 찾으려고 할 때

In [51]:
dir(pd)

['BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_hashtable',
 '_is_numpy_dev',
 '_lib',
 '_libs',
 '_np_version_under1p14',
 '_np_version_under1p15',
 '_np_version_under1p16',
 '_np_version_under1p17',
 '_np_version_under1p18',
 '_testing',
 '_tslib',
 '_typing',
 '_version',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

## merge

* copy() : df 할당은 데이터 할당이 아님. 데이터를 할당하려면 copy()를 사용해야 함

In [59]:
wti = original.copy()

In [61]:
tmp = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
              'B': ['B0', 'B1', 'B2', 'B3'],
              'C': ['C0', 'C1', 'C2', 'C3'],
              'D': ['D0', 'D1', 'D2', 'D3']},
              index=[0, 1, 2, 3])

In [62]:
tmp

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [63]:
tmp2 = tmp.iloc[2:, :]
tmp2

    A   B   C   D
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [64]:
tmp2.iloc[1,3]

'D3'

In [65]:
tmp2.iloc[1,3] = 'X'

c:\Users\Administrator\work\venv\lib\site-packages\pandas\core\indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
c:\Users\Administrator\work\venv\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [66]:
tmp2

    A   B   C   D
2  A2  B2  C2  D2
3  A3  B3  C3   X

In [67]:
tmp

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3   X

In [69]:
s1 = tmp.iloc[2:, :].copy()

In [71]:
s1.iloc[1,3] = 'Y'

In [72]:
s1

    A   B   C   D
2  A2  B2  C2  D2
3  A3  B3  C3   Y

In [73]:
tmp

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3   X

* copy()는 원본에 영향을 미치지 않는 독립된 새로운 df를 만드는 방법
* 그렇지 않고, 기존 df에서 일부를 할당할 경우, 할당된 데이터의 변경이 기존 df에 영향을 미치게 됨

In [81]:
original_wti.head(3)

           날짜   파실 때  보내실 때   받으실 때
0  2020.05.26  34.35   1.10  +3.30%
1  2020.05.22  33.25   0.67  -1.97%
2  2020.05.21  33.92   0.43  +1.28%

In [82]:
original_sk_df.head(3)

           날짜        종가      전일비        시가        고가        저가        거래량
1  2020.05.27  122000.0   1000.0  122500.0  129000.0  118000.0  1853126.0
2  2020.05.26  121000.0  15000.0  106000.0  122500.0  105500.0  2739083.0
3  2020.05.25  106000.0   2500.0  104000.0  106500.0  102000.0   564404.0

In [84]:
original_wti.merge(original_sk_df)

,날짜,파실 때,보내실 때,받으실 때,종가,전일비,시가,고가,저가,거래량
0,2020.05.26,34.35,1.10,+3.30%,121000.0,15000.0,106000.0,122500.0,105500.0,2739083.0
1,2020.05.22,33.25,0.67,-1.97%,103500.0,3000.0,106500.0,107000.0,102000.0,686662.0
2,2020.05.21,33.92,0.43,+1.28%,106500.0,3000.0,106000.0,110000.0,105500.0,1120684.0
3,2020.05.20,33.49,1.53,+4.78%,103500.0,0.0,101500.0,104500.0,101000.0,614306.0
4,2020.05.19,31.96,0.31,+0.97%,103500.0,6700.0,101500.0,104000.0,100000.0,1724747.0
5,2020.05.18,31.82,2.39,+8.12%,96800.0,2400.0,96000.0,96900.0,94400.0,567019.0
6,2020.05.15,29.43,1.87,+6.78%,94400.0,800.0,94900.0,96000.0,94200.0,480497.0
7,2020.05.14,27.56,2.27,+8.97%,93600.0,1900.0,94500.0,94800.0,93000.0,490652.0
8,2020.05.13,25.29,0.49,-1.90%,95500.0,100.0,95000.0,95500.0,93000.0,608052.0
9,2020.05.12,25.78,1.64,+6.79%,95400.0,2100.0,97000.0,97400.0,95000.0,642196.0
10,2020.05.11,24.14,0.60,-2.42%,97500.0,1100.0,99200.0,99600.0,97500.0,466477.0
11,2020.05.08,24.74,1.19,+5.05%,98600.0,100.0,99000.0,99500.0,98600.0,448962.0
12,2020.05.07,23.55,0.44,-1.83%,98700.0,1300.0,99200.0,99500.0,97800.0,670766.0
13,2020.05.06,23.99,0.57,-2.32%,100000.0,3300.0,99200.0,103000.0,99200.0,1419621.0
14,2020.05.04,20.39,0.61,+3.08%,96700.0,1600.0,99900.0,99900.0,96500.0,831689.0
15,2020.04.29,15.06,2.72,+22.04%,98300.0,1800.0,97000.0,100500.0,97000.0,889335.0
16,2020.04.28,12.34,0.44,-3.44%,96500.0,1100.0,96200.0,97700.0,95700.0,655250.0
17,2020.04.27,12.78,4.16,-24.55%,97600.0,0.0,97600.0,98900.0,97600.0,454652.0
18,2020.04.24,16.94,0.44,+2.66%,97600.0,1800.0,100500.0,101000.0,97500.0,619467.0
19,2020.04.23,16.50,2.72,+19.73%,99400.0,3100.0,98700.0,100000.0,97300.0,914524.0
20,2020.04.22,13.78,2.21,+19.10%,96300.0,2200.0,96500.0,97300.0,95100.0,751758.0
21,2020.04.21,10.01,47.64,+126.60%,98500.0,500.0,97500.0,101000.0,95300.0,975923.0
22,2020.04.20,-37.63,55.90,-305.96%,99000.0,1300.0,99200.0,102500.0,98300.0,898140.0
23,2020.04.17,18.27,1.60,-8.05%,97700.0,1000.0,97300.0,98500.0,97100.0,878699.0
24,2020.04.16,19.87,0.00,0.00%,96700.0,500.0,95300.0,98000.0,94300.0,733830.0
25,2020.04.14,20.11,2.30,-10.26%,97200.0,900.0,97100.0,99300.0,96500.0,682589.0
26,2020.04.13,22.41,0.35,-1.53%,96300.0,4200.0,99800.0,100500.0,95800.0,778610.0
27,2020.04.09,22.76,2.33,-9.28%,98000.0,4400.0,96800.0,98000.0,95000.0,1180802.0
28,2020.04.08,25.09,1.46,+6.17%,93600.0,700.0,92600.0,95900.0,92200.0,828451.0
29,2020.04.07,23.63,2.45,-9.39%,94300.0,100.0,96500.0,96900.0,91900.0,1161168.0
30,2020.04.06,26.08,2.26,-7.97%,94400.0,4700.0,91100.0,95500.0,90000.0,1393130.0

In [85]:
original_wti.merge(original_sk_df, on = ['날짜'])

,날짜,파실 때,보내실 때,받으실 때,종가,전일비,시가,고가,저가,거래량
0,2020.05.26,34.35,1.10,+3.30%,121000.0,15000.0,106000.0,122500.0,105500.0,2739083.0
1,2020.05.22,33.25,0.67,-1.97%,103500.0,3000.0,106500.0,107000.0,102000.0,686662.0
2,2020.05.21,33.92,0.43,+1.28%,106500.0,3000.0,106000.0,110000.0,105500.0,1120684.0
3,2020.05.20,33.49,1.53,+4.78%,103500.0,0.0,101500.0,104500.0,101000.0,614306.0
4,2020.05.19,31.96,0.31,+0.97%,103500.0,6700.0,101500.0,104000.0,100000.0,1724747.0
5,2020.05.18,31.82,2.39,+8.12%,96800.0,2400.0,96000.0,96900.0,94400.0,567019.0
6,2020.05.15,29.43,1.87,+6.78%,94400.0,800.0,94900.0,96000.0,94200.0,480497.0
7,2020.05.14,27.56,2.27,+8.97%,93600.0,1900.0,94500.0,94800.0,93000.0,490652.0
8,2020.05.13,25.29,0.49,-1.90%,95500.0,100.0,95000.0,95500.0,93000.0,608052.0
9,2020.05.12,25.78,1.64,+6.79%,95400.0,2100.0,97000.0,97400.0,95000.0,642196.0
10,2020.05.11,24.14,0.60,-2.42%,97500.0,1100.0,99200.0,99600.0,97500.0,466477.0
11,2020.05.08,24.74,1.19,+5.05%,98600.0,100.0,99000.0,99500.0,98600.0,448962.0
12,2020.05.07,23.55,0.44,-1.83%,98700.0,1300.0,99200.0,99500.0,97800.0,670766.0
13,2020.05.06,23.99,0.57,-2.32%,100000.0,3300.0,99200.0,103000.0,99200.0,1419621.0
14,2020.05.04,20.39,0.61,+3.08%,96700.0,1600.0,99900.0,99900.0,96500.0,831689.0
15,2020.04.29,15.06,2.72,+22.04%,98300.0,1800.0,97000.0,100500.0,97000.0,889335.0
16,2020.04.28,12.34,0.44,-3.44%,96500.0,1100.0,96200.0,97700.0,95700.0,655250.0
17,2020.04.27,12.78,4.16,-24.55%,97600.0,0.0,97600.0,98900.0,97600.0,454652.0
18,2020.04.24,16.94,0.44,+2.66%,97600.0,1800.0,100500.0,101000.0,97500.0,619467.0
19,2020.04.23,16.50,2.72,+19.73%,99400.0,3100.0,98700.0,100000.0,97300.0,914524.0
20,2020.04.22,13.78,2.21,+19.10%,96300.0,2200.0,96500.0,97300.0,95100.0,751758.0
21,2020.04.21,10.01,47.64,+126.60%,98500.0,500.0,97500.0,101000.0,95300.0,975923.0
22,2020.04.20,-37.63,55.90,-305.96%,99000.0,1300.0,99200.0,102500.0,98300.0,898140.0
23,2020.04.17,18.27,1.60,-8.05%,97700.0,1000.0,97300.0,98500.0,97100.0,878699.0
24,2020.04.16,19.87,0.00,0.00%,96700.0,500.0,95300.0,98000.0,94300.0,733830.0
25,2020.04.14,20.11,2.30,-10.26%,97200.0,900.0,97100.0,99300.0,96500.0,682589.0
26,2020.04.13,22.41,0.35,-1.53%,96300.0,4200.0,99800.0,100500.0,95800.0,778610.0
27,2020.04.09,22.76,2.33,-9.28%,98000.0,4400.0,96800.0,98000.0,95000.0,1180802.0
28,2020.04.08,25.09,1.46,+6.17%,93600.0,700.0,92600.0,95900.0,92200.0,828451.0
29,2020.04.07,23.63,2.45,-9.39%,94300.0,100.0,96500.0,96900.0,91900.0,1161168.0
30,2020.04.06,26.08,2.26,-7.97%,94400.0,4700.0,91100.0,95500.0,90000.0,1393130.0

In [88]:
original_wti.merge(original_sk_df, how = 'outer', on = ['날짜'])

,날짜,파실 때,보내실 때,받으실 때,종가,전일비,시가,고가,저가,거래량
0,2020.05.26,34.35,1.10,+3.30%,121000.0,15000.0,106000.0,122500.0,105500.0,2739083.0
1,2020.05.22,33.25,0.67,-1.97%,103500.0,3000.0,106500.0,107000.0,102000.0,686662.0
2,2020.05.21,33.92,0.43,+1.28%,106500.0,3000.0,106000.0,110000.0,105500.0,1120684.0
3,2020.05.20,33.49,1.53,+4.78%,103500.0,0.0,101500.0,104500.0,101000.0,614306.0
4,2020.05.19,31.96,0.31,+0.97%,103500.0,6700.0,101500.0,104000.0,100000.0,1724747.0
5,2020.05.18,31.82,2.39,+8.12%,96800.0,2400.0,96000.0,96900.0,94400.0,567019.0
6,2020.05.15,29.43,1.87,+6.78%,94400.0,800.0,94900.0,96000.0,94200.0,480497.0
7,2020.05.14,27.56,2.27,+8.97%,93600.0,1900.0,94500.0,94800.0,93000.0,490652.0
8,2020.05.13,25.29,0.49,-1.90%,95500.0,100.0,95000.0,95500.0,93000.0,608052.0
9,2020.05.12,25.78,1.64,+6.79%,95400.0,2100.0,97000.0,97400.0,95000.0,642196.0
10,2020.05.11,24.14,0.60,-2.42%,97500.0,1100.0,99200.0,99600.0,97500.0,466477.0
11,2020.05.08,24.74,1.19,+5.05%,98600.0,100.0,99000.0,99500.0,98600.0,448962.0
12,2020.05.07,23.55,0.44,-1.83%,98700.0,1300.0,99200.0,99500.0,97800.0,670766.0
13,2020.05.06,23.99,0.57,-2.32%,100000.0,3300.0,99200.0,103000.0,99200.0,1419621.0
14,2020.05.05,24.56,4.17,+20.45%,NaN,NaN,NaN,NaN,NaN,NaN
15,2020.05.04,20.39,0.61,+3.08%,96700.0,1600.0,99900.0,99900.0,96500.0,831689.0
16,2020.05.01,19.78,0.94,+4.98%,NaN,NaN,NaN,NaN,NaN,NaN
17,2020.04.30,18.84,3.78,+25.09%,NaN,NaN,NaN,NaN,NaN,NaN
18,2020.04.29,15.06,2.72,+22.04%,98300.0,1800.0,97000.0,100500.0,97000.0,889335.0
19,2020.04.28,12.34,0.44,-3.44%,96500.0,1100.0,96200.0,97700.0,95700.0,655250.0
20,2020.04.27,12.78,4.16,-24.55%,97600.0,0.0,97600.0,98900.0,97600.0,454652.0
21,2020.04.24,16.94,0.44,+2.66%,97600.0,1800.0,100500.0,101000.0,97500.0,619467.0
22,2020.04.23,16.50,2.72,+19.73%,99400.0,3100.0,98700.0,100000.0,97300.0,914524.0
23,2020.04.22,13.78,2.21,+19.10%,96300.0,2200.0,96500.0,97300.0,95100.0,751758.0
24,2020.04.21,10.01,47.64,+126.60%,98500.0,500.0,97500.0,101000.0,95300.0,975923.0
25,2020.04.20,-37.63,55.90,-305.96%,99000.0,1300.0,99200.0,102500.0,98300.0,898140.0
26,2020.04.17,18.27,1.60,-8.05%,97700.0,1000.0,97300.0,98500.0,97100.0,878699.0
27,2020.04.16,19.87,0.00,0.00%,96700.0,500.0,95300.0,98000.0,94300.0,733830.0
28,2020.04.15,19.87,0.24,-1.19%,NaN,NaN,NaN,NaN,NaN,NaN
29,2020.04.14,20.11,2.30,-10.26%,97200.0,900.0,97100.0,99300.0,96500.0,682589.0
30,2020.04.13,22.41,0.35,-1.53%,96300.0,4200.0,99800.0,100500.0,95800.0,778610.0
31,2020.04.09,22.76,2.33,-9.28%,98000.0,4400.0,96800.0,98000.0,95000.0,1180802.0
32,2020.04.08,25.09,1.46,+6.17%,93600.0,700.0,92600.0,95900.0,92200.0,828451.0
33,2020.04.07,23.63,2.45,-9.39%,94300.0,100.0,96500.0,96900.0,91900.0,1161168.0
34,2020.04.06,26.08,2.26,-7.97%,94400.0,4700.0,91100.0,95500.0,90000.0,1393130.0
35,2020.05.27,NaN,NaN,NaN,122000.0,1000.0,122500.0,129000.0,118000.0,1853126.0
36,2020.05.25,NaN,NaN,NaN,106000.0,2500.0,104000.0,106500.0,102000.0,564404.0
37,2020.04.10,NaN,NaN,NaN,100500.0,2500.0,95300.0,101500.0,95300.0,1300475.0
38,2020.04.03,NaN,NaN,NaN,89700.0,700.0,95800.0,98500.0,87800.0,1788505.0
39,2020.04.02,NaN,NaN,NaN,90400.0,7900.0,83100.0,93500.0,81400.0,2074973.0
40,2020.04.01,NaN,NaN,NaN,82500.0,4500.0,85100.0,87000.0,82500.0,835614.0
41,2020.03.31,NaN,NaN,NaN,87000.0,900.0,88000.0,88200.0,84500.0,1027447.0
42,2020.03.30,NaN,NaN,NaN,86100.0,1600.0,83400.0,87700.0,81700.0,1151182.0
43,2020.03.27,NaN,NaN,NaN,87700.0,2700.0,89600.0,90500.0,85200.0,1746990.0
44,2020.03.26,NaN,NaN,NaN,85000.0,5000.0,91000.0,100500.0,84900.0,3277516.0
45,2020.03.25,NaN,NaN,NaN,90000.0,18000.0,79000.0,91300.0,75700.0,2877009.0
46,2020.03.24,NaN,NaN,NaN,72000.0,11700.0,63100.0,73200.0,61500.0,1571585.0
47,2020.03.23,NaN,NaN,NaN,60300.0,4500.0,58500.0,62900.0,57800.0,1162459.0
48,2020.03.20,NaN,NaN,NaN,64800.0,7500.0,61000.0,65100.0,59100.0,1719407.0
49,2020.03.19,NaN,NaN,NaN,57300.0,13600.0,70900.0,72300.0,55100.0,2188651.0
50,2020.03.18,NaN,NaN,NaN,70900.0,7000.0,77300.0,77800.0,70900.0,919817.0
51,2020.03.17,NaN,NaN,NaN,77900.0,2300.0,75100.0,79400.0,75100.0,1006085.0
52,2020.03.16,NaN,NaN,NaN,80200.0,6300.0,86000.0,86900.0,80200.0,1113686.0
53,2020.03.13,NaN,NaN,NaN,86500.0,5900.0,83300.0,87200.0,82500.0,1232107.0